name: Build and Push Container Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'Containerfile'
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: redhat-actions/buildah-build@v2
        with:
          image: sainnhe/dotfiles
          tags: latest
          containerfiles: ./Containerfile
      - name: Push to Docker Hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: sainnhe/dotfiles
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: sainnhe/dotfiles
          tags: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
