name: Build and Push Container Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'Containerfile'
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Buildah action
        uses: actions/checkout@v2
        with:
          path: "buildah-build"
      - name: Install latest buildah
        run: |
          sudo apt-get update -qq
          sudo apt-get -qq -y install buildah
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Build image
        uses: ./buildah-build/
        with:
          image: sainnhe/dotfiles
          tags: latest
          platforms: linux/arm64/v8
          containerfiles: ./Containerfile
      - name: Push to Docker Hub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: sainnhe/dotfiles
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: sainnhe/dotfiles
          tags: latest
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
